import{a as p,S as v,i as d}from"./assets/vendor-CSTHH2rc.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&m(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function m(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const h=s=>s.map(e=>`
      <li class="gallery-card">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="gallery-info">
          <p class="info-item"><strong>Likes</strong> ${e.likes}</p>
          <p class="info-item"><strong>Views</strong> ${e.views}</p>
          <p class="info-item"><strong>Comments</strong> ${e.comments}</p>
          <p class="info-item"><strong>Downloads</strong> ${e.downloads}</p>
        </div>
      </li>
      `).join("");p.defaults.baseURL="https://pixabay.com/api/";const f=(s,e)=>{const a={key:"48231881-acbb1e4446b49c7b538272001",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return p.get("https://pixabay.com/api/",{params:a})},y=document.querySelector(".js-search-form"),i=document.querySelector(".js-gallery"),L=new v(".gallery a",{captionsData:"alt",captionDelay:250}),o=document.querySelector(".js-load-more"),g=document.querySelector(".js-loader");let c=1,n="",b=0;const q=async s=>{try{if(s.preventDefault(),n=s.currentTarget.elements.user_query.value.trim(),!n||n===""){d.error({title:"❌",message:"Please enter your query!",position:"topRight",icon:""});return}i.innerHTML="",g.classList.remove("is-hidden"),c=1,o.classList.add("is-hidden");const e=await f(n,c);if(g.classList.add("is-hidden"),e.data.total===0){d.error({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",icon:""}),i.innerHTML="",y.reset();return}e.data.totalHits>15&&(o.classList.remove("is-hidden"),o.addEventListener("click",u)),i.innerHTML=h(e.data.hits),b=i.querySelector("li").getBoundingClientRect().height,o.classList.remove("is-hidden"),o.addEventListener("click",u),L.refresh()}catch(e){console.log(e),s.currentTarget.reset()}};y.addEventListener("submit",q);const u=async s=>{try{c++;const e=await f(n,c);i.insertAdjacentHTML("beforeend",h(e.data.hits)),scrollBy({top:b*2,behavior:"smooth"});const a=Math.ceil(e.data.totalHits/15);if(c===a){o.classList.add("is-hidden"),o.removeEventListener("click",u),d.error({title:"❌",message:"We're sorry, but you've reached the end of search results.",position:"topRight",icon:""});return}L.refresh()}catch(e){console.log(e)}};
//# sourceMappingURL=index.js.map
