import{a as p,S as v,i as u}from"./assets/vendor-CSTHH2rc.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))g(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&g(d)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function g(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const h=r=>r.map(e=>`
      <li class="gallery-card">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="gallery-info">
          <p class="info-item"><strong>Likes</strong> ${e.likes}</p>
          <p class="info-item"><strong>Views</strong> ${e.views}</p>
          <p class="info-item"><strong>Comments</strong> ${e.comments}</p>
          <p class="info-item"><strong>Downloads</strong> ${e.downloads}</p>
        </div>
      </li>
      `).join("");p.defaults.baseURL="https://pixabay.com/api/";const f=(r,e)=>{const i={key:"48231881-acbb1e4446b49c7b538272001",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return p.get("https://pixabay.com/api/",{params:i})},y=document.querySelector(".js-search-form"),a=document.querySelector(".js-gallery"),L=new v(".gallery a",{captionsData:"alt",captionDelay:250}),o=document.querySelector(".js-load-more"),c=document.querySelector(".js-loader");let l=1,n="",b=0;const q=async r=>{try{if(r.preventDefault(),n=r.currentTarget.elements.user_query.value.trim(),!n||n===""){u.error({title:"❌",message:"Please enter your query!",position:"topRight",icon:""});return}a.innerHTML="",c.classList.remove("is-hidden"),l=1,o.classList.add("is-hidden");const e=await f(n,l);if(c.classList.add("is-hidden"),e.data.total===0){u.error({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",icon:""}),a.innerHTML="",y.reset();return}e.data.totalHits>15&&(o.classList.remove("is-hidden"),o.addEventListener("click",m)),a.innerHTML=h(e.data.hits),b=a.querySelector("li").getBoundingClientRect().height,o.classList.remove("is-hidden"),o.addEventListener("click",m),L.refresh()}catch(e){console.log(e),r.currentTarget.reset()}};y.addEventListener("submit",q);const m=async r=>{try{o.classList.add("is-hidden"),c.classList.remove("is-hidden"),l++;const e=await f(n,l);a.insertAdjacentHTML("beforeend",h(e.data.hits)),scrollBy({top:b*2,behavior:"smooth"});const i=Math.ceil(e.data.totalHits/15);if(l===i){o.classList.add("is-hidden"),o.removeEventListener("click",m),u.error({title:"❌",message:"We're sorry, but you've reached the end of search results.",position:"topRight",icon:""}),c.classList.add("is-hidden");return}c.classList.add("is-hidden"),o.classList.remove("is-hidden"),L.refresh()}catch(e){console.log(e)}};
//# sourceMappingURL=index.js.map
